config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "games#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :games, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
    member do
      post :play
      get :loading
      get :results
      get :final
    end

    resources :rounds, only: [:show]

    resources :users, only: [:show]

  end
  resources :questions do
    post "submit_answer", on: :member
  end
  resources :users, only: [] do
    collection do
      get :search
    end
  end
  get "boxers", to: "pages#boxers"

  get "boxers/:nickname", to: "users#show", as: :nickname

end

app/models/round.rb
class Round < ApplicationRecord
  after_save :set_question, unless: :seeding?
  belongs_to :game
  has_one :question

  private

  def seeding?
    ENV['SEEDING'] == 'true'
  end

  def set_question
    Question.create(round_id: self.id)
  end

end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def show
    @game = Game.find(params[:game_id])
    @round = Round.find(params[:id])
    @question = @round.question
    @answers = @question.answers
    @game_player = @game.game_players.where(user: current_user)
    @opponent_player = @game.game_players.where.not(user: current_user).first
    # # selected_answer = Answer.find(params[:answer_id])

    # if selected_answer.correct?
    #   @game_player = @game.game_players.find_by(user: current_user)
    # end
    # next_round = Round.where('id > ?', @round.id).first
    @next_round = @game.rounds.find_by(round_number: @round.round_number + 1)


    # if next_round
    #   redirect_to game_round_path(@game, next_round)
    # else
    #   redirect_to games_path
    # end
  end
end

app/views/rounds/show.html.erb
<div class="round-header">
<div class="round-avatar">
<%= image_tag url_for(@game.game_players.first.user.avatar),class:'github' %>
<span class="vs"><%= image_tag "versus" %></span>
<%= image_tag url_for(@game.game_players.second.user.avatar), class: 'github' %></div>
<h1 class="text-center">Round <%= @round.round_number %></h1>
</div>
<div class="all">
<div class="form-container game-card question-card">
  <% if @question %>
    <p class="question-content"><%= @question.content %></p>
    <%= form_with url: submit_answer_question_path(@question) do %>
      <div class="answer-buttons">
        <% @question.answers.each do |answer| %>
          <% id = "answer_#{answer.id}" %>
          <%= radio_button_tag 'answer_id', answer.id, id: id, class: 'hidden-radio' %>
          <label for="<%= id %>" class="selectable-btn">
            <%= answer.content %>
          </label>
        <% end %>
      </div>
      <div class="text-center">
        <%= submit_tag "Submit", class: 'submit-btn' %>
      </div>
    <% end %>
  <% else %>

    <p class="no-question">No question available.</p></div>
  <% end %>
</div>