config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "games#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :games, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
    member do
      post :play
      get :loading
      get :results
      get :final
    end

    resources :rounds, only: [:show]

    resources :users, only: [:show]

  end
  resources :questions do
    post "submit_answer", on: :member
  end
  resources :users, only: [] do
    collection do
      get :search
    end
  end
  get "boxers", to: "pages#boxers"

  get "boxers/:nickname", to: "users#show", as: :nickname

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :game
  has_many :game_players
  has_many :player_answers
  has_many :games_as_opponent, class_name: 'Game', foreign_key: 'opponent_id'
  has_many :messages
  has_one_attached :avatar

  def total_score
    game_players.sum(:score)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def search
    @users = User.where('name LIKE ?', "%#{params[:query]}%").limit(10)
    render json: @users
  end

  def show
    @other_user = User.find_by(nickname: params[:nickname])
    @shared_games = Game.shared_between(current_user, @other_user)

    @my_games = @shared_games.joins(:game_players)
                      .where(game_players: { user_id: current_user.id, played: false })
                      .group('games.id, game_players.id')

    # Games that both players have completed (assuming complete? is a model method)
    @complete_games = @shared_games.select { |game| game.complete? }

  end

end

app/views/users/show.html.erb
<h1>Games against <%= @other_user.nickname %></h1>
<% if @shared_games.any? %>
  <div class="game-list">
    <h2>You haven't thrown a punch</h2>
    <div class="game-card boxing-card">
        <div class="game-info">
          <h2>Time to start a fight?</h2>
        </div>
      </div>
    <% @my_games.each do |game| %>
      <div class="game-card boxing-card">
        <div class="game-info">
          <div class="player">
            <span class="player-email"><%= game.game_players.first.user.nickname %></span>
            <%= image_tag url_for(game.game_players.first.user.avatar),class:'githubsmall' %>
            <span class="player-score"><%= game.game_players.first.score %></span>
          </div>
          <span class="vs">
            <%= link_to 'Play Now', game_round_path(game, game.rounds.first), class: 'btn play-now-btn', role: 'button' %>
          </span>
          <div class="player">
            <span class="player-email"><%= game.game_players.second.user.nickname %></span>
            <%= image_tag url_for(game.game_players.second.user.avatar),class:'githubsmall' %>
            <span class="player-score"><%= game.game_players.second.score %></span>
          </div>
        </div>
      </div>
    <% end %>
    <h2>Match over</h2>
    <% @complete_games.each do |game| %>
      <div class="game-card boxing-card">
        <div class="game-info">
          <%= link_to game_path(game) , class: "navbar-icon" do %>
            <div class="player">
              <%= image_tag 'belt.png', class:"belt" if game.game_players.first.score > game.game_players.second.score%>
              <%= image_tag 'ko.png', class:"belt" if game.game_players.first.score < game.game_players.second.score%>
              <span class="player-email"><%= game.game_players.first.user.nickname %></span>
              <span class="player-score <%= "winner" if game.game_players.first.score > game.game_players.second.score%>"><%= game.game_players.first.score %></span>
            </div>
            <span class="vs"><%= image_tag "boxing-gloves.png" %></span>
            <div class="player">
              <%= image_tag 'belt.png', class:"belt" if game.game_players.first.score < game.game_players.second.score%>
              <%= image_tag 'ko.png', class:"belt" if game.game_players.first.score > game.game_players.second.score%>
              <span class="player-email"><%= game.game_players.second.user.nickname %></span>
              <span class="player-score <%= "winner" if game.game_players.first.score < game.game_players.second.score%>"><%= game.game_players.second.score %></span>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h3>No games with this user.</h3>
  <h3>Start one?</h3>
<% end %>