config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "games#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :games, only: [:index, :show, :new, :create] do
    resources :messages, only: :create
    member do
      post :play
      get :loading
      get :results
      get :final
    end

    resources :rounds, only: [:show]

    resources :users, only: [:show]

  end
  resources :questions do
    post "submit_answer", on: :member
  end
  resources :users, only: [] do
    collection do
      get :search
    end
  end
  get "boxers", to: "pages#boxers"

  get "boxers/:nickname", to: "users#show", as: :nickname

end

app/models/game.rb
class Game < ApplicationRecord
  after_create :set_rounds, unless: :seeding?
  belongs_to :user
  belongs_to :opponent, class_name: 'User'

  has_many :game_players
  has_many :rounds
  has_many :game_categories
  has_many :categories, through: :game_categories
  has_many :questions, through: :rounds

  has_many :users, through: :game_players, as: :players
  has_many :players, through: :game_players, source: :user

  has_many :messages, dependent: :destroy
  belongs_to :user

  def seeding?
    ENV['SEEDING'] == 'true'
  end

  def set_rounds
    SetRoundsJob.perform_later(self)
  end

  def current_round
    rounds.order(:round_number).last
  end

  scope :shared_between, ->(user1, user2) {
    where(user_id: [user1.id, user2.id], opponent_id: [user1.id, user2.id])
  } 


  def current_player
    game_players.find_by(user_id: user.id)
  end

  def opponent_player
    game_players.find_by(user_id: opponent.id)
  end

  def complete?
    current_player.played && opponent_player.played
  end

  def winner!
    # self.game_players
    # if the current user of the game wins, they will be assigned the winner_id
    if current_player.score > opponent_player.score
      update(winner_id: user.id)
      winner_user = user
    elsif current_player.score < opponent_player.score
      update(winner_id: opponent_player.user.id)
      winner_user = opponent
    else
      winner_user = nil
    end
    # else the opponent will get it
    # Or if the score is the same then the match will be considered a draw
    # Ensure there are players in the game
    return winner_user
  end

  def questions_content
    string = questions.map do |question|
      question.content
    end
    string.join("; ")

  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show]
  def index
    # Fetch all games where the user is either the main user or the opponent
    @games = Game.where("games.user_id = ? OR games.opponent_id = ?", current_user.id, current_user.id)

    # Games that the current user hasn't played
    @my_games = @games.joins(:game_players)
                      .where(game_players: { user_id: current_user.id, played: false })
                      .group('games.id, game_players.id')

    @started_games = Game.joins(:game_players)
    .where(game_players: { user_id: current_user.id, played: true })  # Current user has played
    .where.not(id: Game.joins(:game_players)
                        .where("game_players.user_id != ?", current_user.id)  # Ensure we are checking for the opponent
                        .where(game_players: { played: true }))  # Exclude games where the opponent has played
    .group('games.id')




    # Games that both players have completed (assuming complete? is a model method)
    @complete_games = @games.select { |game| game.complete? }
  end



  def show
    @game_players = @game.game_players.includes(:user)
    @rounds = @game.rounds.includes(:questions)
    @message = Message.new
  end

  def new
    @categories = Category.all
    @users = []
    User.all.each do |user|
      if user != current_user
        @users << user.nickname
      end
    end
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.user = current_user

    @opponent = User.find_by(nickname: game_params[:user_id])

    if @opponent.nil?
      flash[:alert] = "Opponent not found. Please select a valid opponent."
      render :new and return
    end

    @game.opponent_id = @opponent.id


    if @game.save
      GamePlayer.create!(game: @game, user: current_user)
      GamePlayer.create!(game: @game, user: @opponent)
      redirect_to loading_game_path(@game)
    else
      render :new
    end
  end

  def play
    @game = Game.find(params[:id])
    redirect_to game_round_path(@game, @game.rounds.first), notice: "Game has started!"
  end

  def loading
    @game = Game.find(params[:id])
    @first_round = @game.rounds.first
  end

  def results
    @game = Game.find(params[:id])
    @rounds = @game.rounds.count
    if current_user == @game.current_player.user
      @score = @game.current_player.score
    else
      @score = @game.opponent_player.score
    end
  end

  def final
    @game = Game.find(params[:id])

    @winner = @game.winner!

  end

  private

  def set_game
    @game = Game.find_by(id: params[:id])
    redirect_to games_path, alert: "Game not found." unless @game
  end

  def game_params
    params.require(:game).permit(:user_id, category_ids: [])
  end
end

app/views/games/_ready.html.erb
<div class="container mt-5">
  <div id="<%= dom_id(game) %>" class="game-container">
    <%= turbo_stream_from dom_id(game) %>

    <% if game.rounds.any? %>
      <%= link_to "Play", game_round_path(game, game.rounds.first), class: "play-button" %>
    <% else %>
      <%= image_tag 'warmup', class: 'ready-image' %>
    <% end % %>
  </div>
</div>

app/views/games/_winner.html.erb
<div id="winner_<%= dom_id(game)%>" >
  <%= turbo_stream_from "winner_#{dom_id(game)}" %>
  <% if game.complete? %>
    <%= link_to 'The champion is..', final_game_path(game), class: 'btn btn-danger', role: 'button' %>
  <% else  %>
    <h3>Waiting for your opponent to strike...</h3>
  <% end %>
  <%# raise %>
</div>

app/views/games/final.html.erb
<div class="results-container text-center">
  <% if @winner.nil? %>
    <!--style for draw-->
    <h1>It's a draw!</h1>
  <% elsif @winner == current_user %>
    <h1>You won!</h1>
    <!--style for 'you won'-->
  <% else %>
    <!--style for 'you lost'-->
    <h1><%= @winner.nickname %> won!</h1>
  <% end %>
  <br>
  <br>
  <br>
  <br>
  <h2>Your total score </h2>
  <h2>is now</h2>
  <h2><%= current_user.total_score %></h2>
  <br>
  <br>
  <br>
  <h3>Ready for another round?</h3>
</div>

app/views/games/index.html.erb
<div class="game-list">
  <h2>You haven't thrown a punch</h2>
  <% @my_games.each do |game| %>
    <div class="game-card boxing-card">
      <div class="game-info">
        <div class="player">

          <span class="player-email"><%= game.game_players.first.user.nickname %></span>
          <%= image_tag url_for(game.game_players.first.user.avatar),class:'githubsmall' %>
          <span class="player-score mt-1"><%= game.game_players.first.score %></span>
        </div>

        <span class="vs">
          <%= link_to 'Play Now', game_round_path(game, game.rounds.first), class: 'btn play-now-btn', role: 'button' %>
        </span>

        <div class="player">
          <span class="player-email"><%= game.game_players.second.user.nickname %></span>
          <%= image_tag url_for(game.game_players.second.user.avatar),class:'githubsmall' %>
          <span class="player-score mt-1"><%= game.game_players.second.score %></span>
        </div>
      </div>
    </div>
  <% end %>

  <h2>Waiting for punch </h2>
  <% @started_games.each do |game| %>

    <div class="game-card boxing-card">
      <div class="game-info">
        <div class="player">
          <span class="player-email"><%= game.game_players.first.user.nickname %></span>
          <%= image_tag url_for(game.game_players.first.user.avatar),class:'githubsmall' %>
          <span class="player-score mt-1"><%= game.game_players.first.score %></span>
        </div>


        <span class="vs"><%= image_tag "boxing-gloves.png" %></span>


        <div class="player">
          <span class="player-email"><%= game.game_players.second.user.nickname %></span>
          <%= image_tag url_for(game.game_players.second.user.avatar),class:'githubsmall' %>
          <span class="player-score mt-1"><%= game.game_players.second.score %></span>

        </div>
      </div>
    </div>
  <% end %>

  <h2>Match over</h2>

  <% @complete_games.each do |game| %>
    <div class="game-card boxing-card">
      <div class="game-info">
        <%= link_to game_path(game), class: "navbar-icon" do %>
        <div class="player">
          <%= image_tag 'belt.png', class:"belt" if game.game_players.first.score > game.game_players.second.score%>
          <%= image_tag 'ko.png', class:"belt" if game.game_players.first.score < game.game_players.second.score%>
          <span class="player-email"><%= game.game_players.first.user.nickname %></span>
          <span class="player-score <%= "winner" if game.game_players.first.score > game.game_players.second.score%>"><%= game.game_players.first.score %></span>
        </div>
        <span class="vs"><%= image_tag "boxing-gloves.png" %></span>
        <div class="player">
          <%= image_tag 'belt.png', class:"belt" if game.game_players.first.score < game.game_players.second.score%>
          <%= image_tag 'ko.png', class:"belt" if game.game_players.first.score > game.game_players.second.score%>
          <span class="player-email"><%= game.game_players.second.user.nickname %></span>
          <span class="player-score <%= "winner" if game.game_players.first.score < game.game_players.second.score%>"><%= game.game_players.second.score %></span>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/loading.html.erb
<div class="load mt-5">
  <h1 class="text-center">GLOVES READY?</h1>


  <div class="play-button-container mt-3">
    <%= render 'ready', game: @game %>
    <%#= link_to "Play", game_round_path(@game, @game.rounds.first),class:"play-button"  %>
  </div>
  <h2 class="text-center">Generating AI questions...</h2>
</div>

app/views/games/new.html.erb
<h1 class="text-center">Step into the ring</h1>
<div class="game-card">
  <div class="new-game-container">
    <%= simple_form_for(@game) do |f| %>
      <div class="field">
        <%= f.input :user_id,
            label: "Challenger",
            as: :select,
            collection: @users,
            input_html: {
              id: 'challenger-search',
              class: 'form-control text-center'
            },
            include_blank: 'Select opponent' %>
      </div>
      <div class="field">
        <%= f.input :category_ids, collection: @categories, as: :check_boxes, label: "Select Categories" %>
      </div>
      <div class="actions text-center">
        <%= f.submit "FIGHT", class: "btn submit-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/games/results.html.erb
<div class="results-container">
  <h1 class="text-center">Game over </h1>
  <h2>You answered</h2>
  <h2><%= @score %> / <%= @rounds %> </h2>

  <h2>questions correctly</h2>
  <br>
  <br>
  <br>
  <br>
  <%= render 'winner', game: @game %>
  </div>
</div>

app/views/games/show.html.erb
<div class="game-card p-3">
  <%= turbo_stream_from "game_#{@game.id}_messages" %>
  <div id="messages" class="messages-container">
    <% @game.messages.each do |message| %>
      <%= render "messages/message", message: message, user: current_user %>
    <% end %>
  </div>
  <div class="align-form-button"><%= simple_form_for [@game, @message], html: { class: "message-form", data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } } do |f| %>
    <%= f.input :content, label: false, placeholder: "Message the players", wrapper_html: { class: "flex-grow-1" } %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %></div>
  <% end %>
</div>